// <auto-generated />
using System;
using DotnetYuzuncuYil.Repo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotnetYuzuncuYil.Repo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231227151823_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DotnetYuzuncuYil.Core.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Teams", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 12, 27, 18, 18, 23, 634, DateTimeKind.Local).AddTicks(3189),
                            TeamName = "Development"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 12, 27, 18, 18, 23, 634, DateTimeKind.Local).AddTicks(3202),
                            TeamName = "Sales"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 12, 27, 18, 18, 23, 634, DateTimeKind.Local).AddTicks(3205),
                            TeamName = "Marketing"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 12, 27, 18, 18, 23, 634, DateTimeKind.Local).AddTicks(3207),
                            TeamName = "HR"
                        });
                });

            modelBuilder.Entity("DotnetYuzuncuYil.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 12, 27, 18, 18, 23, 634, DateTimeKind.Local).AddTicks(4030),
                            Email = "buse@gmail.com",
                            Password = "123456",
                            TeamId = 1,
                            UserName = "buse"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 12, 27, 18, 18, 23, 634, DateTimeKind.Local).AddTicks(4036),
                            Email = "elnur@gmail.com",
                            Password = "455678",
                            TeamId = 2,
                            UserName = "elnur"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 12, 27, 18, 18, 23, 634, DateTimeKind.Local).AddTicks(4038),
                            Email = "seher@gmail.com",
                            Password = "789456",
                            TeamId = 3,
                            UserName = "seher"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 12, 27, 18, 18, 23, 634, DateTimeKind.Local).AddTicks(4039),
                            Email = "gizem@gmail.com",
                            Password = "874569",
                            TeamId = 4,
                            UserName = "gizem"
                        });
                });

            modelBuilder.Entity("DotnetYuzuncuYil.Core.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserProfiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Buse",
                            LastName = "Sezer",
                            NickName = "bus",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Elnur",
                            LastName = "Akkurt",
                            NickName = "eln",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Seher",
                            LastName = "Tosun",
                            NickName = "b12",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Gizem",
                            LastName = "Turan",
                            NickName = "sherlock",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("DotnetYuzuncuYil.Core.Models.User", b =>
                {
                    b.HasOne("DotnetYuzuncuYil.Core.Models.Team", "Team")
                        .WithMany("User")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DotnetYuzuncuYil.Core.Models.UserProfile", b =>
                {
                    b.HasOne("DotnetYuzuncuYil.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DotnetYuzuncuYil.Core.Models.Team", b =>
                {
                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
